config/routes.rb
Spyglass::Application.routes.draw do

  root :to => 'searches#index'

  resources :searches
  resources :grabs

  match "empty" => "searches#empty"
  
  mount Resque::Server, :at => "/resque"  

end

app/models/grab.rb
class Grab < ActiveRecord::Base

  validates :url, :presence => true

  before_save :find_by_url
    
  def find_by_url
    logger.debug "path: #{self.url}"
    unless self.url.nil?
      agent = mechanize(self.url)
      begin
        case self.url
        when /macys.com/
          get_macys(agent)
        when /bloomingdales.com/
          get_bloomingdales(agent)
        when /sears.ca/
          get_sears(agent)
        when /www.amazon/
          get_amazon(agent)
        end
      rescue Exception => e
        logger.debug e.message
        logger.debug e.backtrace
      end
    end
  end

  private

  def mechanize(url)
    begin
      agent = Mechanize.new
      agent.user_agent_alias = 'Mac Safari'
      agent.read_timeout=2  #set the agent time out
      agent.get(url)
      return agent
    rescue Exception => e
      puts e.message
      puts e.backtrace
      return {}
    end
  end

  def get_macys(agent)
    # http://www1.macys.com/catalog/product/index.ognc?ID=588960&PseudoCat=se-xx-xx-xx.esn_results
    unless agent.nil?
      self.file_type = "tiff"
      loc = agent.page.search(".productImageSection #productFlash img").attr("src").value
      self.asset_path = loc.match(/.*?\?/)[0] + "?op_sharpen=1&wid=800&hei=980"
      logger.debug self.asset_path
    end
  end

  def get_bloomingdales(agent)
    # http://www1.bloomingdales.com/catalog/product/index.ognc?ID=554341&CategoryID=15915
    unless agent.nil?
      logger.debug agent
      self.file_type = "tiff"
      loc = agent.page.search("#mainProductImage").attr("src").value
      logger.debug loc
      self.asset_path = loc.match(/.*?\?/)[0] + "?op_sharpen=1&wid=800&hei=980"
      logger.debug self.asset_path
    end
  end

  def get_sears(agent)
    # http://www.sears.ca/product/protocol-md-long-sleeve-striped-dress-shirt/645-000148783-MF11-PR10-4306
    unless agent.nil?
      self.file_type = "jpg"
      loc = agent.page.search("#productInfo .medium").attr("src").value
      self.asset_path = loc.gsub("Product_271", "Product_437")
    end
  end
  
  def get_amazon(agent)
    # http://www.amazon.ca/gp/product/B00005JM5Z/ref=s9_pop_gw_g74_ir03?pf_rd_m=A3DWYIK6Y9EEQB&pf_rd_s=center-2&pf_rd_r=1T2JV4JEJDCFSA3XXVKK&pf_rd_t=101&pf_rd_p=506427871&pf_rd_i=915398
    unless agent.nil?
      self.file_type = "jpg"
      loc = agent.page.search("#prodImage").attr("src").value
      self.asset_path = loc.gsub("._SL500_AA300_", "")
    end
  end

end

app/models/search.rb
class Search < ActiveRecord::Base

  validates :term, :presence => true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "play" && password == "pen"
    end
  end
end

app/controllers/grabs_controller.rb
class GrabsController < ApplicationController

  layout "images"

  def new
    @grab = Grab.new
  end
  
  def create
    @grab = Grab.create(params[:grab])
    redirect_to :action => 'show', :id => @grab.id
  end

  def show
    @grab = Grab.find(params[:id])

    respond_to do |format|
      format.html
      format.tiff{ generate_asset(@grab) }
      format.jpg{ generate_asset(@grab) }
    end
  end

  def download
    generate_asset(@grab = Grab.find(params[:id]))
  end

  private
  
  def generate_asset(obj)
    require 'open-uri'
    filename = "#{Rails.root}/public/download.#{obj.file_type}"
    File.open(filename, 'wb') do |file|
      file << open(obj.asset_path).read
    end
    send_file filename, :type => "image/#{obj.file_type}", :disposition => "inline"
  end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  layout "searches"

  MAILTO = "john@johnantoni.com"

  def index
    @search = Search.new
    @searches = Search.find(:all)

    respond_to do |format|
      format.html
      format.csv { require 'csv' }
    end

  end

  def create
    @search = Search.new(params[:search])
    if @search.save
      Resque.enqueue(Sku, @search.id)
      redirect_to searches_url, :notice => "Searching for #{@search.term}."
    else
      render :action => 'new'
    end
  end
  
  def destroy
    Search.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

  def empty
    Search.destroy_all
    redirect_to searches_url, :notice => "Cleared all searches"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
    
end

app/views/grabs/_form.html.erb
<%= semantic_form_for @grab do |f| %>

  <%= f.inputs do %>
		<%= f.input :url, :label => false, :required => :true, :as => :text, :input_html => {  :rows => 5, :cols => 140, :placeholder => "http://www.somesite.com", :tabindex => 0 } %>
	<% end %>

	<%= f.buttons do %>
		<%= f.commit_button "Grab Image" %>
	<% end %>

<% end %>

app/views/grabs/new.html.erb
<%= render :partial => "form" %>

app/views/grabs/show.html.erb
<p>
  <%= link_to "Download File", grab_path(:id => @grab.id, :format => @grab.file_type)%>
</p>

<p>
  <%= link_to image_tag(@grab.asset_path), @grab.asset_path %>
</p>

<p>
  <%= link_to "Grab New Image", new_grab_path %>
</p>

app/views/layouts/images.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpyGlass</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div id="container">

		<header>
			<h1>SpyGlass</h1>
			<p>
			  <%=link_to "Product Search", searches_path %>
        <%=link_to "Image Grab", new_grab_path %>
			</p>
		</header>

	  <section>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
			<%= yield %>
		</section>
	
		<footer>
			<small>
				&copy; <%=Time.now.year()%> SpyGlass
			</small>
		</footer>
	</div>

	<script type="text/javascript">

	  // var _gaq = _gaq || [];
	  // _gaq.push(['_setAccount', 'UA-393335-41']);
	  // _gaq.push(['_trackPageview']);
	  // 
	  // (function() {
	  //   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	  //   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	  //   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  // })();

	</script>
	
</body>
</html>

app/views/layouts/searches.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpyGlass</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

	<meta http-equiv="refresh" content="30" />
</head>
<body>

	<div id="container">

		<header>
			<h1>SpyGlass</h1>
			<p>
			  <%=link_to "Product Search", searches_path %>
        <%=link_to "Image Grab", new_image_path %>
			</p>
		</header>

	  <section>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
			<%= yield %>
		</section>
	
		<footer>
			<small>
				&copy; <%=Time.now.year()%> SpyGlass
			</small>
		</footer>
	</div>

	<script type="text/javascript">

	  // var _gaq = _gaq || [];
	  // _gaq.push(['_setAccount', 'UA-393335-41']);
	  // _gaq.push(['_trackPageview']);
	  // 
	  // (function() {
	  //   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	  //   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	  //   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  // })();

	</script>
	
</body>
</html>

app/views/searches/_form.html.erb
<%= semantic_form_for @search do |f| %>
  <%= f.inputs do %>
		<%= f.input :term, :label => "Search Term", :input_html => {  :size => 50, :maxlength => 100, :placeholder => "classic concepts 90187125", :tabindex => 0 } %>
  <% end %>
	<%= f.buttons do %>
		<%= f.commit_button "Search" %>
	<% end %>
  <p></p>
<% end %>

app/views/searches/index.csv.erb
<%- headers = [
	"Term", 
	"WayFair Init",
	"WayFair Sale",
	"WayFair URL",

	"BrookStone Init",
	"BrookStone Sale",
	"BrookStone URL",

	"OverStock Init",
	"OverStock Sale",
	"OverStock URL",

	"Amazon Init",
	"Amazon Sale",
	"Amazon URL",

	"NextTag Init",
	"NextTag Sale",
	"NextTag URL",

	"ShopWiki Init",
	"ShopWiki Sale",
	"ShopWiki URL"
	] -%>
<%= CSV.generate_line headers %>
<%- @searches.each do |item| -%>
<%- row = [ item.term,

            item.wayfair_init_price,
            item.wayfair_sale_price,
            item.wayfair_url,

            item.brookstone_init_price,
            item.brookstone_sale_price,
            item.brookstone_url,

            item.overstock_init_price,
            item.overstock_sale_price,
            item.overstock_url,

            item.amazon_init_price,
            item.amazon_sale_price,
            item.amazon_url,

            item.nexttag_init_price,
            item.nexttag_sale_price,
            item.nexttag_url,

            item.shopwiki_init_price,
            item.shopwiki_sale_price,
            item.shopwiki_url
 ] -%>
<%= CSV.generate_line row %>
<%- end -%>

app/views/searches/index.html.erb
<%= render :partial => "form" %>

<hr/>

<% h "Searches" %>

<table id="line_items">
  <tr>
		<th>Term</th>
    <th>WayFair Init</th>
    <th>WayFair Sale</th>
    <th>BrookStone Init</th>
    <th>BrookStone Sale</th>
    <th>OverStock Init</th>
    <th>OverStock Sale</th>
    <th>Amazon Init</th>
    <th>Amazon Sale</th>
    <th>NextTag Init</th>
    <th>NextTag Sale</th>
    <th>ShopWiki Init</th>
    <th>ShopWiki Sale</th>
  </tr>
<% if !@searches.nil? %>
	<% for item in @searches %>
	<tr class="<%= cycle :odd, :even %>">
		<td><%= item.term %></td>

		<td><%= link_to_if !item.wayfair_url.nil?, item.wayfair_init_price, item.wayfair_url, html_options = { :target => "_blank"} %></td>
		<td><%= link_to_if !item.wayfair_url.nil?, item.wayfair_sale_price, item.wayfair_url, html_options = { :target => "_blank"} %></td>

		<td><%= link_to_if !item.brookstone_url.nil?, item.brookstone_init_price, item.brookstone_url, html_options = { :target => "_blank"} %></td>
		<td><%= link_to_if !item.brookstone_url.nil?, item.brookstone_sale_price, item.brookstone_url, html_options = { :target => "_blank"} %></td>

		<td><%= link_to_if !item.overstock_url.nil?, item.overstock_init_price, item.overstock_url, html_options = { :target => "_blank"} %></td>
		<td><%= link_to_if !item.overstock_url.nil?, item.overstock_sale_price, item.overstock_url, html_options = { :target => "_blank"} %></td>

		<td><%= link_to_if !item.amazon_url.nil?, item.amazon_init_price, item.amazon_url, html_options = { :target => "_blank"} %></td>
		<td><%= link_to_if !item.amazon_url.nil?, item.amazon_sale_price, item.amazon_url, html_options = { :target => "_blank"} %></td>

		<td><%= link_to_if !item.nexttag_url.nil?, item.nexttag_init_price, item.nexttag_url, html_options = { :target => "_blank"} %></td>
		<td><%= link_to_if !item.nexttag_url.nil?, item.nexttag_sale_price, item.nexttag_url, html_options = { :target => "_blank"} %></td>

		<td><%= link_to_if !item.shopwiki_url.nil?, item.shopwiki_init_price, item.shopwiki_url, html_options = { :target => "_blank"} %></td>
		<td><%= link_to_if !item.shopwiki_url.nil?, item.shopwiki_sale_price, item.shopwiki_url, html_options = { :target => "_blank"} %></td>

	</tr>
	<% end %>
<% end %>
</table>

<nav>
	<ul>
		<li><%= link_to "Download", searches_path(:format => :csv), html_options = { :target => "_blank"} %></li>
		<li><%= link_to "Delete", "/empty", :confirm => 'Are you sure?' %></li>
	</ul>
</nav>